#define CHORDAL_HOLD
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "bmZvQ/ZPK5pz"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

